<div>
    <h1>Invoice Details for Customer <?php echo $block->getCustomerId(); ?></h1>
    <?php $invoiceDetails = $block->getInvoiceDetails(); ?>
    
    <?php if (isset($invoiceDetails['error'])): ?>
        <p><?= $invoiceDetails['error'] ?></p>
    <?php else: ?>
        <table border="1">
            <tr>
                <th>Invoice Number</th>
                <th>Invoice Total</th>
                <th>Customer Email</th>
                <th>Customer Name</th>
                <th>Invoice Date</th>
                
            </tr>
            <?php foreach ($invoiceDetails as $data) { ?>
            <tr>
                <td><?= $data['invoice_number'] ?></td>
                <td><?= $data['amount'] ?></td>
                <td><?= $data['customer_email'] ?></td>
                <td><?= $data['customer_name'] ?></td>
                <td><?= $data['invoice_date']?></td>
               
            </tr>
            <?php } ?>
        </table>
    <?php endif; ?>
</div>
